# Generated by Django 5.0.6 on 2024-05-24 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='similarityscore',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='similarityscore',
            name='compared_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compared_similarity_scores', to='similarity_api.usertext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarityscore',
            name='user_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores', to='similarity_api.usertext'),
            preserve_default=False,
        ),
    ]
